namespace FleetPlanner.Models;

/// <summary>
/// The scope at which a recommendation applies.
/// </summary>
public enum RecommendationScope
{
    /// <summary>Recommendation targets a single ship.</summary>
    Ship,

    /// <summary>Recommendation targets a specific fleet group.</summary>
    Group,

    /// <summary>Recommendation targets the entire account/collection.</summary>
    Account
}

/// <summary>
/// The kind of analysis that produced a recommendation.
/// Each maps to one of the 10 analytical patterns.
/// </summary>
public enum RecommendationKind
{
    /// <summary>Group has doctrine tag but lacks ships with matching capability.</summary>
    CapabilityGap,

    /// <summary>Multiple ships in a group carry the same primary role tag.</summary>
    Redundancy,

    /// <summary>A ship's role tags would strengthen a group that lacks that role.</summary>
    Complement,

    /// <summary>Owned ship has fewer than 2 tags (excluding acquisition).</summary>
    UnderDescribedShip,

    /// <summary>Owned ship not in any group and has been in collection > 7 days.</summary>
    UnassignedShip,

    /// <summary>Group's ship role tags align poorly with group's doctrine tags.</summary>
    GroupCoherence,

    /// <summary>Whole collection lacks ships in major role categories.</summary>
    AccountRoleDistribution,

    /// <summary>Ship's primary doctrine tag conflicts with its group's doctrine tags.</summary>
    DoctrineMismatch,

    /// <summary>Ship contributes nothing to a group based on group doctrine + ship tags.</summary>
    RemoveFromGroup,

    /// <summary>Group's required crew total vs. group.CrewTarget mismatch.</summary>
    CrewEfficiency
}

/// <summary>
/// Priority level for a recommendation.
/// </summary>
public enum RecommendationPriority
{
    /// <summary>Nice-to-have suggestion.</summary>
    Low,

    /// <summary>Meaningful improvement.</summary>
    Medium,

    /// <summary>Critical gap or issue.</summary>
    High
}

/// <summary>
/// A recommendation generated by the graph-driven recommendation engine.
/// Recommendations are ephemeral — computed fresh and not persisted.
/// </summary>
public class Recommendation
{
    /// <summary>Unique identifier for this recommendation instance.</summary>
    public string RecommendationId { get; set; } = Guid.NewGuid().ToString();

    /// <summary>The scope at which this recommendation applies.</summary>
    public RecommendationScope ScopeType { get; set; }

    /// <summary>OwnedShipId or GroupId depending on scope. Null for Account scope.</summary>
    public int? ScopeId { get; set; }

    /// <summary>The kind of analysis that produced this recommendation.</summary>
    public RecommendationKind Kind { get; set; }

    /// <summary>Catalogue ship Id of a suggested ship, if applicable.</summary>
    public int? TargetShipId { get; set; }

    /// <summary>Tag key relevant to this recommendation, if applicable.</summary>
    public string? TargetTagKey { get; set; }

    /// <summary>Normalised score from 0.0 to 1.0.</summary>
    public double Score { get; set; }

    /// <summary>Derived priority based on score.</summary>
    public RecommendationPriority Priority { get; set; }

    /// <summary>Short, actionable summary.</summary>
    public string Summary { get; set; } = string.Empty;

    /// <summary>Detailed explanation of why this recommendation was made.</summary>
    public string Explanation { get; set; } = string.Empty;

    /// <summary>Evidence data points supporting this recommendation.</summary>
    public List<string> Evidence { get; set; } = new();

    /// <summary>Suggested actions the user can take.</summary>
    public List<string> SuggestedActions { get; set; } = new();
}
