namespace FleetPlanner.Models;

/// <summary>
/// The scope at which a recommendation applies. Determines what entity
/// <see cref="Recommendation.ScopeId"/> refers to.
/// </summary>
public enum RecommendationScope
{
    /// <summary>Recommendation targets a single ship.</summary>
    Ship,

    /// <summary>Recommendation targets a specific fleet group.</summary>
    Group,

    /// <summary>Recommendation targets the entire account/collection.</summary>
    Account
}

/// <summary>
/// The kind of analysis that produced a recommendation. Each value maps to one of the
/// 12 analytical patterns in <see cref="FleetPlanner.Services.RecommendationService"/>.
/// See the pattern method documentation for trigger conditions, scoring, and edge cases.
/// Patterns 11 (TradeoffSuggestions) and 12 (PotencyMismatches) reuse existing kinds
/// to emit recommendations for tradeoff and potency-related findings.
/// </summary>
public enum RecommendationKind
{
    /// <summary>Group has doctrine tag but lacks ships with matching capability.</summary>
    CapabilityGap,

    /// <summary>Multiple ships in a group carry the same primary role tag.</summary>
    Redundancy,

    /// <summary>A ship's role tags would strengthen a group that lacks that role.</summary>
    Complement,

    /// <summary>Owned ship has fewer than 2 tags (excluding acquisition).</summary>
    UnderDescribedShip,

    /// <summary>Owned ship not in any group and has been in collection > 7 days.</summary>
    UnassignedShip,

    /// <summary>Group's ship role tags align poorly with group's doctrine tags.</summary>
    GroupCoherence,

    /// <summary>Whole collection lacks ships in major role categories.</summary>
    AccountRoleDistribution,

    /// <summary>Ship's primary doctrine tag conflicts with its group's doctrine tags.</summary>
    DoctrineMismatch,

    /// <summary>Ship contributes nothing to a group based on group doctrine + ship tags.</summary>
    RemoveFromGroup,

    /// <summary>Group's required crew total vs. group.CrewTarget mismatch.</summary>
    CrewEfficiency
}

/// <summary>
/// Priority level for a recommendation, derived from <see cref="Recommendation.Score"/>.
/// Typically: Score ≥ 0.7 → High, 0.4–0.7 → Medium, &lt; 0.4 → Low. Individual patterns
/// may override this mapping.
/// </summary>
public enum RecommendationPriority
{
    /// <summary>Nice-to-have suggestion.</summary>
    Low,

    /// <summary>Meaningful improvement.</summary>
    Medium,

    /// <summary>Critical gap or issue.</summary>
    High
}

/// <summary>
/// A recommendation generated by the graph-driven <see cref="FleetPlanner.Services.IRecommendationService"/>.
/// Recommendations are ephemeral — computed fresh on each analysis run and never persisted to SQLite.
///
/// <para><b>Score semantics:</b> <see cref="Score"/> is a normalised value in the 0.0–1.0 range.
/// Higher scores indicate more actionable findings. The score is derived from constants in
/// <see cref="FleetPlanner.Services.RecommendationWeights"/>, sometimes scaled by a ratio
/// (e.g. coherence percentage). <see cref="Priority"/> is derived from the score, typically:
/// ≥ 0.7 → <see cref="RecommendationPriority.High"/>, 0.4–0.7 → Medium, &lt; 0.4 → Low,
/// though individual patterns may override this mapping.</para>
///
/// <para><b>Scope:</b> <see cref="ScopeType"/> determines what the recommendation targets:
/// a specific ship (<see cref="RecommendationScope.Ship"/>), a group
/// (<see cref="RecommendationScope.Group"/>), or the entire account
/// (<see cref="RecommendationScope.Account"/>). <see cref="ScopeId"/> holds the entity Id
/// for Ship/Group scopes and is null for Account scope.</para>
/// </summary>
public class Recommendation
{
    /// <summary>Unique identifier for this recommendation instance.</summary>
    public string RecommendationId { get; set; } = Guid.NewGuid().ToString();

    /// <summary>The scope at which this recommendation applies.</summary>
    public RecommendationScope ScopeType { get; set; }

    /// <summary>OwnedShipId or GroupId depending on scope. Null for Account scope.</summary>
    public int? ScopeId { get; set; }

    /// <summary>The kind of analysis that produced this recommendation.</summary>
    public RecommendationKind Kind { get; set; }

    /// <summary>Catalogue ship Id of a suggested ship, if applicable.</summary>
    public int? TargetShipId { get; set; }

    /// <summary>Tag key relevant to this recommendation, if applicable.</summary>
    public string? TargetTagKey { get; set; }

    /// <summary>Normalised score from 0.0 to 1.0.</summary>
    public double Score { get; set; }

    /// <summary>Derived priority based on score.</summary>
    public RecommendationPriority Priority { get; set; }

    /// <summary>Short, actionable summary.</summary>
    public string Summary { get; set; } = string.Empty;

    /// <summary>Detailed explanation of why this recommendation was made.</summary>
    public string Explanation { get; set; } = string.Empty;

    /// <summary>Evidence data points supporting this recommendation.</summary>
    public List<string> Evidence { get; set; } = new();

    /// <summary>Suggested actions the user can take.</summary>
    public List<string> SuggestedActions { get; set; } = new();
}
