namespace FleetPlanner.Models;

/// <summary>
/// Priority level for a recommendation. Higher-priority recommendations appear first
/// in the UI and represent more urgent gaps in the fleet.
/// </summary>
public enum RecommendationPriority
{
    /// <summary>Nice-to-have suggestion — the fleet functions fine without it.</summary>
    Low,

    /// <summary>Meaningful improvement — filling this gap would noticeably strengthen the fleet.</summary>
    Medium,

    /// <summary>Critical gap — the fleet is missing a core capability for its declared focus.</summary>
    High
}

/// <summary>
/// The type of analysis that produced a recommendation. Each category corresponds to
/// a distinct algorithm in <see cref="FleetPlanner.Services.RecommendationService"/>.
/// </summary>
public enum RecommendationCategory
{
    /// <summary>
    /// A declared <see cref="FleetRole"/> has no ships (or insufficient ships) covering it.
    /// Generated by the focus-aware role gap analysis.
    /// </summary>
    RoleCoverage,

    /// <summary>
    /// The fleet would benefit from ships that complement existing ones —
    /// e.g., adding an escort fighter to protect a mining operation.
    /// </summary>
    FleetSynergy,

    /// <summary>
    /// An existing ship could be upgraded to a better version within the same role
    /// (e.g., Prospector → MOLE for a mining fleet that now has enough crew).
    /// </summary>
    UpgradePath,

    /// <summary>
    /// Cost-effectiveness and value analysis — identifies ships that deliver strong
    /// capability-per-dollar or capability-per-aUEC for the fleet's needs.
    /// </summary>
    ValueAnalysis,

    /// <summary>
    /// The fleet's total crew demand vs. available crew budget.
    /// Flags over-crewed fleets and suggests more crew-efficient alternatives.
    /// </summary>
    CrewEfficiency
}

/// <summary>
/// A recommendation generated on-device by the <see cref="FleetPlanner.Services.RecommendationService"/>.
/// <para>
/// Recommendations are ephemeral — they are computed fresh each time the user views the
/// Recommendations page and are NOT persisted to SQLite. This keeps them always up-to-date
/// with the current fleet state.
/// </para>
/// <para>
/// Each recommendation has a <see cref="Category"/> (what kind of analysis produced it),
/// a <see cref="Priority"/>, a human-readable explanation, and optionally a list of
/// <see cref="SuggestedShips"/> that would address the identified gap.
/// </para>
/// </summary>
public class Recommendation
{
    /// <summary>Short, actionable title shown as the recommendation header (e.g., "Add a Dedicated Miner").</summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Detailed explanation of WHY this recommendation was made and HOW the suggested ships address the gap.
    /// This is the educational payload — it should help the user understand fleet composition strategy.
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>Which analysis algorithm produced this recommendation.</summary>
    public RecommendationCategory Category { get; set; }

    /// <summary>How urgently the fleet needs this change.</summary>
    public RecommendationPriority Priority { get; set; }

    /// <summary>
    /// Ships that would address this recommendation. May be empty if the recommendation is
    /// purely informational (e.g., a crew efficiency warning with no specific ship suggestion).
    /// </summary>
    public List<Ship> SuggestedShips { get; set; } = [];

    /// <summary>
    /// Optional note about crew impact — e.g., "This ship requires 3 crew; you have 2 available."
    /// Shown in the UI to help the user understand crew budget implications.
    /// </summary>
    public string? CrewNote { get; set; }

    /// <summary>
    /// Optional note about how to acquire the suggested ship — pledge store price, aUEC cost,
    /// or whether it's available as a loaner.
    /// </summary>
    public string? AcquisitionNote { get; set; }

    /// <summary>
    /// The fleet this recommendation was generated for.
    /// Used to associate recommendations with the correct fleet in the UI.
    /// </summary>
    public int FleetId { get; set; }
}
