namespace FleetPlanner;

/// <summary>
/// The root Application class for the MAUI app.
/// <para>
/// <b>.NET 9 MAUI pattern:</b> In .NET 9, the recommended way to set the app's root page is
/// to override <see cref="CreateWindow"/> instead of setting the legacy <c>MainPage</c> property.
/// The <c>MainPage</c> property was deprecated in .NET 8 MAUI and removed in .NET 9.
/// </para>
/// <para>
/// <b>InitializeComponent():</b> This is generated by the XAML compiler. It loads and applies
/// the resources defined in <c>App.xaml</c> (the merged resource dictionaries for Colors and Styles).
/// Without this call, no app-level styles or colours would be available.
/// </para>
/// </summary>
/// <see href="https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/app-lifecycle"/>
public partial class App : Application
{
    /// <summary>
    /// Constructor — loads the XAML-defined resources (colours, styles) from <c>App.xaml</c>.
    /// </summary>
    public App()
    {
        InitializeComponent();
    }

    /// <summary>
    /// Creates the app's main window with <see cref="AppShell"/> as the root page.
    /// <para>
    /// <b>Why resolve AppShell from DI?</b> Instead of <c>new AppShell()</c>, we use
    /// <c>IPlatformApplication.Current!.Services.GetRequiredService&lt;AppShell&gt;()</c>.
    /// This ensures AppShell (and any dependencies it might have in the future) are resolved
    /// through the DI container, keeping the app consistent with the DI-everywhere pattern.
    /// </para>
    /// <para>
    /// <c>IPlatformApplication.Current</c> is the MAUI-provided accessor for the running app's
    /// service provider. It's available after <c>MauiApp.CreateBuilder().Build()</c> completes.
    /// </para>
    /// </summary>
    /// <param name="activationState">Platform-specific activation context (not used here).</param>
    /// <returns>A new <see cref="Window"/> wrapping the app shell.</returns>
    protected override Window CreateWindow(IActivationState? activationState)
    {
        // Resolve AppShell from the DI container rather than constructing it directly.
        var shell = IPlatformApplication.Current!.Services.GetRequiredService<AppShell>();
        return new Window(shell);
    }
}
