using System.Collections.ObjectModel;

using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;

using FleetPlanner.Models;
using FleetPlanner.Repositories;
using FleetPlanner.Services;

namespace FleetPlanner.ViewModels;

/// <summary>
/// ViewModel for the Recommendations page — loads fleet data and runs the recommendation engine.
/// <para>
/// <b>Data flow:</b>
/// <list type="number">
///   <item>Load all fleets from the repository.</item>
///   <item>User selects a fleet (or auto-select the first one).</item>
///   <item>Load that fleet's ships and resolve them against the ship catalogue.</item>
///   <item>Pass the fleet, owned ships, and full catalogue to <see cref="IRecommendationService"/>.</item>
///   <item>Display the resulting recommendations in the UI.</item>
/// </list>
/// </para>
/// <para>
/// <b>ObservableObject:</b> The base class from CommunityToolkit.Mvvm that implements
/// <see cref="System.ComponentModel.INotifyPropertyChanged"/>. When a property changes,
/// the MAUI binding engine automatically updates the UI. You never need to manually
/// implement <c>INotifyPropertyChanged</c> when using this base class + <c>[ObservableProperty]</c>.
/// </para>
/// </summary>
/// <see href="https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/"/>
/// <see href="https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.inotifypropertychanged"/>
public partial class RecommendationsViewModel : ObservableObject
{
    /// <summary>For loading fleets and fleet-ship mappings from SQLite.</summary>
    private readonly IFleetRepository _fleetRepository;

    /// <summary>For loading the ship catalogue (names, stats, roles) from cache.</summary>
    private readonly IShipDataService _shipDataService;

    /// <summary>The on-device recommendation engine that analyses fleet composition.</summary>
    private readonly IRecommendationService _recommendationService;

    /// <summary>The generated recommendations displayed in the CollectionView.</summary>
    [ObservableProperty]
    private ObservableCollection<Recommendation> _recommendations = [];

    /// <summary>True while loading — drives a loading indicator in the View.</summary>
    [ObservableProperty]
    private bool _isLoading;

    /// <summary>True when the selected fleet has no ships or no recommendations could be generated.</summary>
    [ObservableProperty]
    private bool _isEmpty;

    /// <summary>True when no fleets exist at all — prompts the user to create one first.</summary>
    [ObservableProperty]
    private bool _hasNoFleet;

    /// <summary>All available fleets — populates the fleet picker in the View.</summary>
    [ObservableProperty]
    private ObservableCollection<Fleet> _fleets = [];

    /// <summary>
    /// The fleet currently selected in the picker. Changing this triggers
    /// <see cref="OnSelectedFleetChanged"/> which re-runs the recommendation engine.
    /// </summary>
    [ObservableProperty]
    private Fleet? _selectedFleet;

    /// <summary>
    /// A human-readable summary of the selected fleet's configuration
    /// (e.g., "Combat fleet — 4 players — Small scale"). Displayed as a subtitle in the View.
    /// </summary>
    [ObservableProperty]
    private string _fleetSummary = string.Empty;

    /// <summary>
    /// Constructor — receives all three dependencies from the DI container.
    /// </summary>
    /// <param name="fleetRepository">For loading fleet and fleet-ship data.</param>
    /// <param name="shipDataService">For loading the cached ship catalogue.</param>
    /// <param name="recommendationService">The recommendation engine.</param>
    public RecommendationsViewModel(
        IFleetRepository fleetRepository,
        IShipDataService shipDataService,
        IRecommendationService recommendationService)
    {
        _fleetRepository = fleetRepository;
        _shipDataService = shipDataService;
        _recommendationService = recommendationService;
    }

    /// <summary>
    /// Called automatically when <see cref="SelectedFleet"/> changes (generated by <c>[ObservableProperty]</c>).
    /// <para>
    /// This is a partial method hook — the source generator creates the property and calls this method
    /// after the value is set. We use it to trigger a recommendation refresh whenever the user
    /// picks a different fleet from the dropdown.
    /// </para>
    /// </summary>
    /// <param name="value">The newly selected fleet, or null.</param>
    /// <see href="https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/generators/observableproperty"/>
    partial void OnSelectedFleetChanged(Fleet? value)
    {
        if (value is not null)
            LoadRecommendationsCommand.Execute(null);
    }

    /// <summary>
    /// Main loading method — fetches fleets, resolves ships, and runs the recommendation engine.
    /// <para>
    /// <b>Algorithm:</b>
    /// <list type="number">
    ///   <item>Load all fleets. If none exist, show "no fleet" state and bail.</item>
    ///   <item>If no fleet is selected yet, auto-select the first one and return
    ///     (the <see cref="OnSelectedFleetChanged"/> handler will re-trigger this method).</item>
    ///   <item>Load the full ship catalogue and build an ID→Ship dictionary for O(1) lookups.</item>
    ///   <item>Load the fleet's FleetShip records and resolve each to a Ship reference.</item>
    ///   <item>Pass everything to the recommendation engine.</item>
    ///   <item>Display the results.</item>
    /// </list>
    /// </para>
    /// </summary>
    [RelayCommand]
    private async Task LoadRecommendationsAsync()
    {
        IsLoading = true;
        try
        {
            var fleets = await _fleetRepository.GetAllFleetsAsync();
            Fleets = new ObservableCollection<Fleet>(fleets);

            if (fleets.Count == 0)
            {
                HasNoFleet = true;
                IsEmpty = true;
                Recommendations = [];
                return;
            }

            HasNoFleet = false;

            // Auto-select the first fleet if none is selected.
            // Setting SelectedFleet triggers OnSelectedFleetChanged, which calls this method again,
            // so we return early to avoid duplicate work.
            if (SelectedFleet is null)
            {
                SelectedFleet = fleets[0];
                return;
            }

            var fleet = SelectedFleet;
            FleetSummary = $"{fleet.PrimaryFocusEnum} fleet — {fleet.AvailableCrewCount} players — {fleet.OperatingScaleEnum} scale";

            // Build a dictionary for O(1) ship lookups by ID.
            // This is faster than repeated .FirstOrDefault() calls when resolving fleet ships.
            var allShips = await _shipDataService.GetAllShipsAsync();
            var shipLookup = allShips.ToDictionary(s => s.Id);

            // Resolve FleetShip → Ship: for each FleetShip in the fleet, look up its Ship reference.
            // Filter out any FleetShips whose ShipId doesn't exist in the catalogue (orphaned data).
            var fleetShips = await _fleetRepository.GetFleetShipsAsync(fleet.Id);
            var ownedShips = fleetShips
                .Where(fs => shipLookup.ContainsKey(fs.ShipId))
                .Select(fs => shipLookup[fs.ShipId])
                .ToList();

            if (ownedShips.Count == 0)
            {
                IsEmpty = true;
                Recommendations = [];
                return;
            }

            // Run the recommendation engine — this is a pure, synchronous computation.
            var recs = _recommendationService.GetRecommendations(fleet, ownedShips, allShips);
            Recommendations = new ObservableCollection<Recommendation>(recs);
            IsEmpty = recs.Count == 0;
        }
        finally
        {
            IsLoading = false;
        }
    }
}
