using FleetPlanner.ViewModels;

namespace FleetPlanner.Views;

/// <summary>
/// Code-behind for the Recommendations page — displays graph-driven fleet
/// improvement suggestions generated by <see cref="Services.IRecommendationService"/>.
/// </summary>
public partial class RecommendationsPage : ContentPage
{
    private readonly RecommendationsViewModel _viewModel;

    /// <summary>
    /// Constructor — receives the ViewModel from DI, loads XAML, and sets the binding context.
    /// </summary>
    public RecommendationsPage(RecommendationsViewModel viewModel)
    {
        InitializeComponent();
        _viewModel = viewModel;
        BindingContext = viewModel;
    }

    /// <summary>
    /// Builds the graph and runs the recommendation engine each time the page appears.
    /// </summary>
    protected override async void OnAppearing()
    {
        base.OnAppearing();
        await _viewModel.LoadRecommendationsCommand.ExecuteAsync(null);
    }
}
